//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BicycleCalculatorWPF.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BicycleCalculatorWPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap _77bikegreens {
            get {
                object obj = ResourceManager.GetObject("_77bikegreens", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap about {
            get {
                object obj = ResourceManager.GetObject("about", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap back {
            get {
                object obj = ResourceManager.GetObject("back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap btn_donateCC_LG {
            get {
                object obj = ResourceManager.GetObject("btn_donateCC_LG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string StringAbout {
            get {
                return ResourceManager.GetString("StringAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Acknowledgement:
        ///德满, 嘻哈, 淘淘爸, citysa, hachi, heiyaa, 楚狂声, bingol, xuchux, 落星, azuretears, blocked, babyfish79, dolphinic, coolsear, 骑楼街5号, enstan007, namrisgan, harvey.hung, pheather, 咸鱼, Seor, kuye 的本地化字符串。
        /// </summary>
        public static string StringAcknow {
            get {
                return ResourceManager.GetString("StringAcknow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add 的本地化字符串。
        /// </summary>
        public static string StringAdd {
            get {
                return ResourceManager.GetString("StringAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Curve 的本地化字符串。
        /// </summary>
        public static string StringAddCurve {
            get {
                return ResourceManager.GetString("StringAddCurve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Donate through AliPay 的本地化字符串。
        /// </summary>
        public static string StringAliPay {
            get {
                return ResourceManager.GetString("StringAliPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cassette Sprockets Branch 的本地化字符串。
        /// </summary>
        public static string StringBranchbk {
            get {
                return ResourceManager.GetString("StringBranchbk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Branch Display 的本地化字符串。
        /// </summary>
        public static string StringBranchDisplay {
            get {
                return ResourceManager.GetString("StringBranchDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Crankset Branch 的本地化字符串。
        /// </summary>
        public static string StringBranchfr {
            get {
                return ResourceManager.GetString("StringBranchfr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Internal Hubs Branch 的本地化字符串。
        /// </summary>
        public static string StringBranchin {
            get {
                return ResourceManager.GetString("StringBranchin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cadence 的本地化字符串。
        /// </summary>
        public static string StringCAD {
            get {
                return ResourceManager.GetString("StringCAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cadence / Speed 的本地化字符串。
        /// </summary>
        public static string StringCadenceSpeed {
            get {
                return ResourceManager.GetString("StringCadenceSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string StringCancel {
            get {
                return ResourceManager.GetString("StringCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cassette Sprockets 的本地化字符串。
        /// </summary>
        public static string StringCassette {
            get {
                return ResourceManager.GetString("StringCassette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Center to left 的本地化字符串。
        /// </summary>
        public static string StringCenterL {
            get {
                return ResourceManager.GetString("StringCenterL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Center to right 的本地化字符串。
        /// </summary>
        public static string StringCenterR {
            get {
                return ResourceManager.GetString("StringCenterR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chart 的本地化字符串。
        /// </summary>
        public static string StringChart {
            get {
                return ResourceManager.GetString("StringChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        public static string StringClose {
            get {
                return ResourceManager.GetString("StringClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Empty Curves 的本地化字符串。
        /// </summary>
        public static string StringClrCurve {
            get {
                return ResourceManager.GetString("StringClrCurve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Column 的本地化字符串。
        /// </summary>
        public static string StringColumn {
            get {
                return ResourceManager.GetString("StringColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This will overwrite the original dataset. It is recommended to backup Data.csv first.
        ///Are you sure to save the dataset? 的本地化字符串。
        /// </summary>
        public static string StringConfirmSave {
            get {
                return ResourceManager.GetString("StringConfirmSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cranksets 的本地化字符串。
        /// </summary>
        public static string StringCranksets {
            get {
                return ResourceManager.GetString("StringCranksets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Crosses 的本地化字符串。
        /// </summary>
        public static string StringCrosses {
            get {
                return ResourceManager.GetString("StringCrosses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current 的本地化字符串。
        /// </summary>
        public static string StringCurrent {
            get {
                return ResourceManager.GetString("StringCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The following curve is already included 的本地化字符串。
        /// </summary>
        public static string StringCurveexist {
            get {
                return ResourceManager.GetString("StringCurveexist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data Source: 的本地化字符串。
        /// </summary>
        public static string StringDataSource {
            get {
                return ResourceManager.GetString("StringDataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default 的本地化字符串。
        /// </summary>
        public static string StringDefault {
            get {
                return ResourceManager.GetString("StringDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string StringDelete {
            get {
                return ResourceManager.GetString("StringDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure to delete the selected items? 的本地化字符串。
        /// </summary>
        public static string StringDeleteSelected {
            get {
                return ResourceManager.GetString("StringDeleteSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display All 的本地化字符串。
        /// </summary>
        public static string StringDisAll {
            get {
                return ResourceManager.GetString("StringDisAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display Items 的本地化字符串。
        /// </summary>
        public static string StringDisItem {
            get {
                return ResourceManager.GetString("StringDisItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Donate 的本地化字符串。
        /// </summary>
        public static string StringDonate {
            get {
                return ResourceManager.GetString("StringDonate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your donation will help this app become better!
        ///Thanks for your donation!
        ///
        ///Click on the button for AliPay or PayPal.
        ///Or scan the dimensional code with AliPay APP.
        ///
        ///AliPay:
        ///carrotkk@sina.com
        ///
        ///PayPal:
        ///carrotkk@sina.com 的本地化字符串。
        /// </summary>
        public static string StringDonateContent {
            get {
                return ResourceManager.GetString("StringDonateContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data Set Edit 的本地化字符串。
        /// </summary>
        public static string StringEditDataSet {
            get {
                return ResourceManager.GetString("StringEditDataSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter the ISO (ETRTO) tire model 的本地化字符串。
        /// </summary>
        public static string StringEnterISO {
            get {
                return ResourceManager.GetString("StringEnterISO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit 的本地化字符串。
        /// </summary>
        public static string StringExit {
            get {
                return ResourceManager.GetString("StringExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export... 的本地化字符串。
        /// </summary>
        public static string StringExport {
            get {
                return ResourceManager.GetString("StringExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to read file. 的本地化字符串。
        /// </summary>
        public static string StringFailReadFile {
            get {
                return ResourceManager.GetString("StringFailReadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File 的本地化字符串。
        /// </summary>
        public static string StringFile {
            get {
                return ResourceManager.GetString("StringFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Left flange ⌀ 的本地化字符串。
        /// </summary>
        public static string StringFlangeL {
            get {
                return ResourceManager.GetString("StringFlangeL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Right flange ⌀ 的本地化字符串。
        /// </summary>
        public static string StringFlangeR {
            get {
                return ResourceManager.GetString("StringFlangeR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gear 的本地化字符串。
        /// </summary>
        public static string StringGear {
            get {
                return ResourceManager.GetString("StringGear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gear Ratio 的本地化字符串。
        /// </summary>
        public static string StringGearRatio {
            get {
                return ResourceManager.GetString("StringGearRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gear (Tooth) 的本地化字符串。
        /// </summary>
        public static string StringGearTeeth {
            get {
                return ResourceManager.GetString("StringGearTeeth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gear Inch 的本地化字符串。
        /// </summary>
        public static string StringGI {
            get {
                return ResourceManager.GetString("StringGI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Help 的本地化字符串。
        /// </summary>
        public static string StringHelp {
            get {
                return ResourceManager.GetString("StringHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1. Select the crankset, Cassette Sprockets, Internal Hub, tires models and cadence, the gear ratio, speed ratio and other parameters will be calculated in real-time and the curve will be drawn automatically.
        ///
        ///2. Check &quot;speed&quot; in the group box &quot;cadence / speed&quot;, the reverse calculation from speed to cadence will be available.
        ///
        ///3. Click &quot;Add current curve&quot; button to add current curve to the chart for comparison, multiple curves can be added.
        ///
        ///4. Click &quot;Export File&quot; to export current configuration and ca [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string StringHelpContent {
            get {
                return ResourceManager.GetString("StringHelpContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hub Hole 的本地化字符串。
        /// </summary>
        public static string StringHubhole {
            get {
                return ResourceManager.GetString("StringHubhole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Left Hub Hole 的本地化字符串。
        /// </summary>
        public static string StringHubHoleL {
            get {
                return ResourceManager.GetString("StringHubHoleL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Right Hub Hole 的本地化字符串。
        /// </summary>
        public static string StringHubHoleR {
            get {
                return ResourceManager.GetString("StringHubHoleR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hub Line 的本地化字符串。
        /// </summary>
        public static string StringHubline {
            get {
                return ResourceManager.GetString("StringHubline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hubs 的本地化字符串。
        /// </summary>
        public static string StringHubs {
            get {
                return ResourceManager.GetString("StringHubs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Increment 的本地化字符串。
        /// </summary>
        public static string StringIncrement {
            get {
                return ResourceManager.GetString("StringIncrement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Internal  的本地化字符串。
        /// </summary>
        public static string StringInner {
            get {
                return ResourceManager.GetString("StringInner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input curve name. 的本地化字符串。
        /// </summary>
        public static string StringInputCName {
            get {
                return ResourceManager.GetString("StringInputCName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Instructions 的本地化字符串。
        /// </summary>
        public static string StringInstructions {
            get {
                return ResourceManager.GetString("StringInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Internal Hub 的本地化字符串。
        /// </summary>
        public static string StringInternalHub {
            get {
                return ResourceManager.GetString("StringInternalHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Such as  47-559 or 1.75-406. 的本地化字符串。
        /// </summary>
        public static string StringISOeg {
            get {
                return ResourceManager.GetString("StringISOeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 In mm or inch, such as 47, 50 or 1.1,1.75. 的本地化字符串。
        /// </summary>
        public static string StringISOmminch {
            get {
                return ResourceManager.GetString("StringISOmminch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        public static string StringLanguage {
            get {
                return ResourceManager.GetString("StringLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Left Side 的本地化字符串。
        /// </summary>
        public static string StringLeft {
            get {
                return ResourceManager.GetString("StringLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Large Crankset with Large Cassette.  的本地化字符串。
        /// </summary>
        public static string StringLFLB {
            get {
                return ResourceManager.GetString("StringLFLB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display Side 的本地化字符串。
        /// </summary>
        public static string StringLRSide {
            get {
                return ResourceManager.GetString("StringLRSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 In mm 的本地化字符串。
        /// </summary>
        public static string Stringmm {
            get {
                return ResourceManager.GetString("Stringmm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Model 的本地化字符串。
        /// </summary>
        public static string StringModel {
            get {
                return ResourceManager.GetString("StringModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modify 的本地化字符串。
        /// </summary>
        public static string StringModify {
            get {
                return ResourceManager.GetString("StringModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MTB 的本地化字符串。
        /// </summary>
        public static string StringMTB {
            get {
                return ResourceManager.GetString("StringMTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 None 的本地化字符串。
        /// </summary>
        public static string StringNone {
            get {
                return ResourceManager.GetString("StringNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        public static string StringOK {
            get {
                return ResourceManager.GetString("StringOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open 的本地化字符串。
        /// </summary>
        public static string StringOpen {
            get {
                return ResourceManager.GetString("StringOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Others 的本地化字符串。
        /// </summary>
        public static string StringOther {
            get {
                return ResourceManager.GetString("StringOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The MIT License (MIT)
        ///
        ///Copyright (c) 2014 OxyPlot
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the &quot;Software&quot;), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
        ///
        ///The above copyright n [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string StringOxyPlotC {
            get {
                return ResourceManager.GetString("StringOxyPlotC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Donate through PayPal 的本地化字符串。
        /// </summary>
        public static string StringPayPal {
            get {
                return ResourceManager.GetString("StringPayPal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Racing 的本地化字符串。
        /// </summary>
        public static string StringRacing {
            get {
                return ResourceManager.GetString("StringRacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ratio 的本地化字符串。
        /// </summary>
        public static string StringRatio {
            get {
                return ResourceManager.GetString("StringRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remark 的本地化字符串。
        /// </summary>
        public static string StringRemark {
            get {
                return ResourceManager.GetString("StringRemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add the current curve after rename? 的本地化字符串。
        /// </summary>
        public static string StringRenameandAdd {
            get {
                return ResourceManager.GetString("StringRenameandAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset All Axes 的本地化字符串。
        /// </summary>
        public static string StringResetAxis {
            get {
                return ResourceManager.GetString("StringResetAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Take effect after restarting the software. 的本地化字符串。
        /// </summary>
        public static string StringRestartEff {
            get {
                return ResourceManager.GetString("StringRestartEff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Result 的本地化字符串。
        /// </summary>
        public static string StringResult {
            get {
                return ResourceManager.GetString("StringResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Right Side 的本地化字符串。
        /// </summary>
        public static string StringRight {
            get {
                return ResourceManager.GetString("StringRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rim diameter 的本地化字符串。
        /// </summary>
        public static string StringRimdiameter {
            get {
                return ResourceManager.GetString("StringRimdiameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 In mm, such as 559,406 的本地化字符串。
        /// </summary>
        public static string StringRimdiametermm {
            get {
                return ResourceManager.GetString("StringRimdiametermm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rim Hole 的本地化字符串。
        /// </summary>
        public static string StringRimhole {
            get {
                return ResourceManager.GetString("StringRimhole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rim Line 的本地化字符串。
        /// </summary>
        public static string StringRimline {
            get {
                return ResourceManager.GetString("StringRimline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rims 的本地化字符串。
        /// </summary>
        public static string StringRims {
            get {
                return ResourceManager.GetString("StringRims", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string StringSave {
            get {
                return ResourceManager.GetString("StringSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select All 的本地化字符串。
        /// </summary>
        public static string StringSelectAll {
            get {
                return ResourceManager.GetString("StringSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Small Crankset with Small Cassette.  的本地化字符串。
        /// </summary>
        public static string StringSFSB {
            get {
                return ResourceManager.GetString("StringSFSB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Size All Columns to Fit 的本地化字符串。
        /// </summary>
        public static string StringSizeToFit {
            get {
                return ResourceManager.GetString("StringSizeToFit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data source of rims and hubs: 
        ///http://bbs.77bike.com/read.php?tid=58657
        ///Data source of cassettes:
        ///http://bbs.77bike.com/read.php?tid=233029 的本地化字符串。
        /// </summary>
        public static string StringSourceRim {
            get {
                return ResourceManager.GetString("StringSourceRim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Speed/Cadence 的本地化字符串。
        /// </summary>
        public static string StringSpdCAD {
            get {
                return ResourceManager.GetString("StringSpdCAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Speed Radio (m) 的本地化字符串。
        /// </summary>
        public static string StringSpdRatio {
            get {
                return ResourceManager.GetString("StringSpdRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Speed 的本地化字符串。
        /// </summary>
        public static string StringSpeed {
            get {
                return ResourceManager.GetString("StringSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Speeds 的本地化字符串。
        /// </summary>
        public static string StringSpeeds {
            get {
                return ResourceManager.GetString("StringSpeeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Spoke hole ⌀ 的本地化字符串。
        /// </summary>
        public static string StringSpokeHole {
            get {
                return ResourceManager.GetString("StringSpokeHole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Left Spokes 的本地化字符串。
        /// </summary>
        public static string StringSpokeL {
            get {
                return ResourceManager.GetString("StringSpokeL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Spoke Length 的本地化字符串。
        /// </summary>
        public static string StringSpokeLength {
            get {
                return ResourceManager.GetString("StringSpokeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Spoke length left 的本地化字符串。
        /// </summary>
        public static string StringSpokeLL {
            get {
                return ResourceManager.GetString("StringSpokeLL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Spoke lenght right 的本地化字符串。
        /// </summary>
        public static string StringSpokeLR {
            get {
                return ResourceManager.GetString("StringSpokeLR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Right Spokes 的本地化字符串。
        /// </summary>
        public static string StringSpokeR {
            get {
                return ResourceManager.GetString("StringSpokeR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Spokes 的本地化字符串。
        /// </summary>
        public static string StringSpokes {
            get {
                return ResourceManager.GetString("StringSpokes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Spokes Data 的本地化字符串。
        /// </summary>
        public static string StringSpokesData {
            get {
                return ResourceManager.GetString("StringSpokesData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Spokes Line 的本地化字符串。
        /// </summary>
        public static string StringSpokesline {
            get {
                return ResourceManager.GetString("StringSpokesline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Teeth 的本地化字符串。
        /// </summary>
        public static string StringTeeth {
            get {
                return ResourceManager.GetString("StringTeeth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tension ratio L/R 的本地化字符串。
        /// </summary>
        public static string StringTenRat {
            get {
                return ResourceManager.GetString("StringTenRat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tire 的本地化字符串。
        /// </summary>
        public static string StringTire {
            get {
                return ResourceManager.GetString("StringTire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tire circumference 的本地化字符串。
        /// </summary>
        public static string StringTireCirc {
            get {
                return ResourceManager.GetString("StringTireCirc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tire width 的本地化字符串。
        /// </summary>
        public static string StringTirewidth {
            get {
                return ResourceManager.GetString("StringTirewidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bicycle Calculator 的本地化字符串。
        /// </summary>
        public static string StringTitle {
            get {
                return ResourceManager.GetString("StringTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Attention to the torque. 的本地化字符串。
        /// </summary>
        public static string StringTorque {
            get {
                return ResourceManager.GetString("StringTorque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Total Cap 的本地化字符串。
        /// </summary>
        public static string StringTotalCap {
            get {
                return ResourceManager.GetString("StringTotalCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Total Diff 的本地化字符串。
        /// </summary>
        public static string StringTotaldiff {
            get {
                return ResourceManager.GetString("StringTotaldiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transmission Data 的本地化字符串。
        /// </summary>
        public static string StringTransData {
            get {
                return ResourceManager.GetString("StringTransData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transmission 的本地化字符串。
        /// </summary>
        public static string StringTransmission {
            get {
                return ResourceManager.GetString("StringTransmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type 的本地化字符串。
        /// </summary>
        public static string StringType {
            get {
                return ResourceManager.GetString("StringType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to export the file. 的本地化字符串。
        /// </summary>
        public static string StringUnableexp {
            get {
                return ResourceManager.GetString("StringUnableexp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unit 的本地化字符串。
        /// </summary>
        public static string StringUnit {
            get {
                return ResourceManager.GetString("StringUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check Update 的本地化字符串。
        /// </summary>
        public static string StringUpdate {
            get {
                return ResourceManager.GetString("StringUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://www.dropbox.com/sh/si098wfev926c0s/AAAHkEnELq0hstPbzjCE7Xgoa 的本地化字符串。
        /// </summary>
        public static string StringUpdateURL {
            get {
                return ResourceManager.GetString("StringUpdateURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version 的本地化字符串。
        /// </summary>
        public static string StringVersion {
            get {
                return ResourceManager.GetString("StringVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View 的本地化字符串。
        /// </summary>
        public static string StringView {
            get {
                return ResourceManager.GetString("StringView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Y-Axis 的本地化字符串。
        /// </summary>
        public static string StringYAxis {
            get {
                return ResourceManager.GetString("StringYAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap 内变速_s1 {
            get {
                object obj = ResourceManager.GetObject("内变速_s1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap 支付宝3sina {
            get {
                object obj = ResourceManager.GetObject("支付宝3sina", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap 牙盘1_s8 {
            get {
                object obj = ResourceManager.GetObject("牙盘1_s8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Icon 自行车计算器 {
            get {
                object obj = ResourceManager.GetObject("自行车计算器", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] 轮胎数据 {
            get {
                object obj = ResourceManager.GetObject("轮胎数据", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap 飞轮_s4 {
            get {
                object obj = ResourceManager.GetObject("飞轮_s4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
